AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  TargetRubyVersion: 2.7

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/rails-data-migrations.rb

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
